### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by HugoGranstrom**

### CODE REVIEW

**Comment by HugoGranstrom** [comment]
Nope doesn't seem like I have any rights here. @mratsim I guess you are the one to ask

**Comment by Vindaar** [comment]
I think it should work now. I've added all SciNim admins as admins for this repository. No idea why that isn't the default.

**Comment by HugoGranstrom** [comment]
It seems to work. Thanks @Vindaar :D 

So everytime one of us creates a new repo we have to manually add the others?

**Comment by mratsim** [comment]
No it's Github. Happens that way for Status repo as well :/.

**Comment by HugoGranstrom** [comment]
That's a shame :/ So organizations are really only an umbrella for packages but not for maintainers as we still have to add everyone manually...

**Comment by Vindaar** [comment]
But unless I'm mistaken every admin can just add the admin group to the repos they create and that's all that's needed.

**Comment by HugoGranstrom** [comment]
Okay that's not too bad after all, could have been worse... 🤔

**Pull request merged**
